name: Tests
on:
  push:
      branches:
      - "**"


jobs:
  pytest:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v6
      
      - name: install dependencies
        run: uv sync
      
      - name: run tests
        run: uv run pytest